name: py36
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.11.4=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.6.13=h12debd9_1
  - readline=8.3=hc2a1206_0
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - casadi==3.7.2
      - dataclasses==0.8
      - decorator==5.1.1
      - jinja2==3.0.3
      - markupsafe==2.0.1
      - numpy==1.19.5
      - opengen==0.9.4
      - py==1.11.0
      - pyyaml==6.0.1
      - retry==0.9.2
      - scipy==1.5.4
